http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "cloudgenius:$2y$05$suNrRm4fx/afsVRl8Dz6q.RE71np9ejNL5XEofHFwIVgYD1Q3J2wu"

# sudo apt install apache2-utils -y
# echo $(htpasswd -nB cloudgenius)
# New password: 123
# Re-type new password: 123
# cloudgenius:$2y$05$suNrRm4fx/afsVRl8Dz6q.RE71np9ejNL5XEofHFwIVgYD1Q3J2wu
