# Traefik static config

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  ssh:
    address: :222

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  cloudflare:
    acme:
      email: nilesh@cloudgeni.us
      storage: "/acme/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    directory: "./dynamic"
    watch: true
